name = "BlockExplorer"
uuid = "226b4d4a-a984-488c-a10c-5334946291f6"
authors = ["emmac <emmettgb@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
